// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsgyoqpzhgzhwnwfekjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzZ3lvcXB6aGd6aHdud2Zla2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MzgwNDUsImV4cCI6MjA3MjQxNDA0NX0.NFMZR3m1ZmWMTsjHNlAAI6fnqDJ8v9ZV7sE6tgIPxkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});